serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444/
  consent: http://127.0.0.1:3000/consent
  login: http://localhost:4455/login
  logout: http://localhost:4455/logut

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

log:
  level: debug
  leak_sensitive_values: true
