version: '3.7'
services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ory
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=platform
    healthcheck:
      test: pg_isready -U ory -d platform
      interval: 5s
      timeout: 1s
      retries: 3
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - intranet
