version: '3.7'
services:
  kratos-postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    healthcheck:
      test: pg_isready -U kratros -d kratos
      interval: 5s
      timeout: 1s
      retries: 3
    networks:
      - intranet